version: '3'
services:
  web:
    image: dariuspetrov97/nginxproxy
    build: ngxproxy/.
    ports:
      - "8080:80"
    depends_on: 
      - "api"
  api:
    image: dariuspetrov97/nodeapp
    build: nodeapp/.
    